/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProcrastinationRouteImport } from './routes/procrastination'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommRouteImport } from './routes/comm'
import { Route as BingoRouteImport } from './routes/bingo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIdRouteImport } from './routes/result.$id'
import { Route as AdminCommunicationRouteImport } from './routes/admin_.communication'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcrastinationRoute = ProcrastinationRouteImport.update({
  id: '/procrastination',
  path: '/procrastination',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommRoute = CommRouteImport.update({
  id: '/comm',
  path: '/comm',
  getParentRoute: () => rootRouteImport,
} as any)
const BingoRoute = BingoRouteImport.update({
  id: '/bingo',
  path: '/bingo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/admin_/communication',
  path: '/admin/communication',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bingo': typeof BingoRoute
  '/comm': typeof CommRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/procrastination': typeof ProcrastinationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test': typeof TestRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bingo': typeof BingoRoute
  '/comm': typeof CommRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/procrastination': typeof ProcrastinationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test': typeof TestRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/bingo': typeof BingoRoute
  '/comm': typeof CommRoute
  '/dashboard': typeof DashboardRoute
  '/privacy': typeof PrivacyRoute
  '/procrastination': typeof ProcrastinationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test': typeof TestRoute
  '/admin_/communication': typeof AdminCommunicationRoute
  '/result/$id': typeof ResultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bingo'
    | '/comm'
    | '/dashboard'
    | '/privacy'
    | '/procrastination'
    | '/reset-password'
    | '/test'
    | '/admin/communication'
    | '/result/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/bingo'
    | '/comm'
    | '/dashboard'
    | '/privacy'
    | '/procrastination'
    | '/reset-password'
    | '/test'
    | '/admin/communication'
    | '/result/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bingo'
    | '/comm'
    | '/dashboard'
    | '/privacy'
    | '/procrastination'
    | '/reset-password'
    | '/test'
    | '/admin_/communication'
    | '/result/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BingoRoute: typeof BingoRoute
  CommRoute: typeof CommRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcrastinationRoute: typeof ProcrastinationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TestRoute: typeof TestRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  ResultIdRoute: typeof ResultIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procrastination': {
      id: '/procrastination'
      path: '/procrastination'
      fullPath: '/procrastination'
      preLoaderRoute: typeof ProcrastinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comm': {
      id: '/comm'
      path: '/comm'
      fullPath: '/comm'
      preLoaderRoute: typeof CommRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bingo': {
      id: '/bingo'
      path: '/bingo'
      fullPath: '/bingo'
      preLoaderRoute: typeof BingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/communication': {
      id: '/admin_/communication'
      path: '/admin/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BingoRoute: BingoRoute,
  CommRoute: CommRoute,
  DashboardRoute: DashboardRoute,
  PrivacyRoute: PrivacyRoute,
  ProcrastinationRoute: ProcrastinationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TestRoute: TestRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  ResultIdRoute: ResultIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
